// ══════════════════════════════════════════════
// GRAMMAR CURRICULUM
// ══════════════════════════════════════════════
const GRAMMAR_MODULES = [
  {
    id: 'a1',
    level: 'A1',
    title: 'A1 Grammar',
    subtitle: 'Foundations: word position, verbs, articles, cases, questions, past forms, and first connectors.',
    outcome: 'You can build simple sentences, ask useful questions, use basic cases, and talk about everyday events in present and past.',
    lessons: [
      {
        id: 'a1-word-position',
        title: 'Word Position',
        focus: 'verb in position 2',
        explanation: 'German word position starts with one rule that pays rent forever: in a normal statement, the conjugated verb stays in position 2. Position 1 can be the subject, a time phrase, a place phrase, or another complete idea.',
        rules: ['Basic statement: subject + verb + rest.', 'If a time/place/detail starts the sentence, the verb still comes next.', 'Use nicht after the verb or later in the sentence to negate actions and descriptions.'],
        examples: [{ de: 'Ich wohne in Berlin.', en: 'I live in Berlin.' }, { de: 'Heute arbeite ich zu Hause.', en: 'Today I am working at home.' }, { de: 'Ich komme morgen nicht.', en: 'I am not coming tomorrow.' }],
        tip: 'Find the conjugated verb first. In an A1 statement, it should be the second idea, even when the first idea is longer than one word.',
        mistakes: ['Do not write Heute ich arbeite. Correct: Heute arbeite ich.', 'Do not treat English word order as the model when a time phrase starts the sentence.'],
        practice: ['Start three sentences with Heute, Morgen, and Am Montag.', 'Rewrite Ich lerne Deutsch with a time phrase at the front.'],
      },
      {
        id: 'a1-verbs',
        title: 'Verbs',
        focus: 'present tense, separable verbs, modal verbs',
        explanation: 'Verbs change by person. The early work includes regular endings, common spelling changes, separable prefixes, irregular verbs, and modal verbs. Learn each verb in short sentences so the ending and word order become automatic.',
        rules: ['Regular present endings: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en.', 'Separable prefixes like an-, auf-, aus-, mit- often move to the end: Ich rufe dich an.', 'With modal verbs, the modal is conjugated and the main verb stays at the end as an infinitive.'],
        examples: [{ de: 'Ich lerne Deutsch.', en: 'I am learning German.' }, { de: 'Sie ruft Michael an.', en: 'She calls Michael.' }, { de: 'Ich muss am Montag arbeiten.', en: 'I have to work on Monday.' }],
        tip: 'Mark separable verbs with a slash when you learn them: an/rufen, mit/bringen, aus/füllen.',
        mistakes: ['Do not forget the separated prefix at the end.', 'Do not conjugate both verbs in a modal sentence: Ich muss arbeiten, not Ich muss arbeite.'],
        practice: ['Conjugate lernen, warten, tanzen, and fahren for ich, du, er, wir, Sie.', 'Make one sentence each with anrufen, müssen, and können.'],
      },
      {
        id: 'a1-articles-nouns-nominative',
        title: 'Articles And Nouns: Nominative',
        focus: 'der, die, das, ein, eine, plural, kein',
        explanation: 'Nominative is the case for the subject and for simple identity sentences. This topic introduces definite articles, indefinite articles, noun capitalization, plural awareness, and kein as noun negation.',
        rules: ['Learn every noun with its article: der Baum, die Tomate, das Museum.', 'Indefinite articles are ein for masculine/neuter and eine for feminine; there is no indefinite plural article.', 'Negate indefinite nouns with kein/keine: Das ist kein Kaffee.'],
        examples: [{ de: 'Der Termin ist heute.', en: 'The appointment is today.' }, { de: 'Das ist kein Kaffee.', en: 'That is not coffee.' }, { de: 'Das sind keine Kinder.', en: 'Those are not children.' }],
        tip: 'The article is part of the word. Learn der Termin, not just Termin.',
        mistakes: ['Do not write German nouns in lowercase.', 'Do not add an indefinite article in plural: eine Kinder is wrong.'],
        practice: ['Collect ten nouns and write each with der, die, or das.', 'Make three nominative sentences with kein/keine.'],
      },
      {
        id: 'a1-building-questions',
        title: 'Building Questions',
        focus: 'W-questions and direction words',
        explanation: 'A1 questions need two patterns: verb-first yes/no questions and W-word questions. Keep wo, wohin, and woher separate so you can ask about location, movement toward a place, and origin.',
        rules: ['Yes/no question: verb + subject + rest?', 'W-question: W-word + verb + subject + rest?', 'Use wo for location, wohin for movement to somewhere, and woher for origin.'],
        examples: [{ de: 'Wer ist das?', en: 'Who is that?' }, { de: 'Was hörst du?', en: 'What are you listening to?' }, { de: 'Wohin gehst du?', en: 'Where are you going?' }],
        tip: 'If the English question uses do/does, German usually moves the real verb to the front.',
        mistakes: ['Do not add a fake helper like do in German.', 'Do not use wo for every where-question when movement or origin is the real meaning.'],
        practice: ['Ask one question with wer, was, wie, wo, wohin, and woher.', 'Turn Ich wohne in Köln into a yes/no question and a W-question.'],
      },
      {
        id: 'a1-adjectives',
        title: 'Adjectives',
        focus: 'S - V - adjective',
        explanation: 'At this stage, adjectives are easiest after the verb: the apple is red, the teacher is friendly, the books are expensive. You can answer with the opposite adjective or with nicht plus the same adjective.',
        rules: ['Predicate adjective pattern: subject + verb + adjective.', 'Use nicht before or near the adjective to negate it.', 'Quantity adverbs like sehr, wirklich, ziemlich, and ein bisschen can stand before adjectives.'],
        examples: [{ de: 'Der Apfel ist rot.', en: 'The apple is red.' }, { de: 'Die Lehrerin ist freundlich.', en: 'The teacher is friendly.' }, { de: 'Die Bücher sind nicht teuer.', en: 'The books are not expensive.' }],
        tip: 'This is the clean A1 adjective pattern because the adjective has no ending after sein.',
        mistakes: ['Do not add adjective endings in this after-the-verb pattern.', 'Do not use kein to negate an adjective; use nicht.'],
        practice: ['Describe five things with ist/sind plus an adjective.', 'Answer three adjective questions once with an opposite and once with nicht.'],
      },
      {
        id: 'a1-articles-nouns-accusative',
        title: 'Articles And Nouns: Accusative',
        focus: 'direct objects',
        explanation: 'Accusative marks the direct object, the thing or person receiving the action. The visible A1 headline is simple but important: masculine der/ein becomes den/einen; feminine, neuter, and plural articles mostly look unchanged.',
        rules: ['Masculine: der Baum -> den Baum, ein Baum -> einen Baum.', 'Feminine, neuter, and plural keep the same basic article forms in accusative.', 'Accusative pronouns change too: mich, dich, ihn, sie, es, uns, euch, sie/Sie.'],
        examples: [{ de: 'Sie isst den Kuchen.', en: 'She eats the cake.' }, { de: 'Ich esse keinen Salat.', en: 'I do not eat salad.' }, { de: 'Ich liebe dich.', en: 'I love you.' }],
        tip: 'Ask who or what receives the action. That answer is usually accusative.',
        mistakes: ['Do not say Ich brauche ein Termin; Termin is masculine, so use einen Termin.', 'Do not change feminine die to der in accusative.'],
        practice: ['Use brauchen, suchen, kaufen with der Termin, die Karte, das Formular.', 'Replace nouns with accusative pronouns in three short sentences.'],
      },
      {
        id: 'a1-possessive-articles',
        title: 'Possessive Articles',
        focus: 'mein, dein, sein, ihr, unser, euer, Ihr',
        explanation: 'Possessive articles say who something belongs to. They stand in front of a noun and decline exactly like ein and kein, so the ending depends on the gender, number, and case of the noun that follows, not on the owner.',
        rules: ['Owner forms: ich -> mein, du -> dein, er/es -> sein, sie -> ihr, wir -> unser, ihr -> euer, sie -> ihr, Sie -> Ihr.', 'They take ein-word endings: feminine and plural add -e (meine Tasche, meine Eltern); masculine and neuter stay bare in nominative (mein Vater, mein Auto).', 'In accusative, only masculine adds -en: Ich suche meinen Schlüssel.'],
        examples: [{ de: 'Das ist mein Auto.', en: 'That is my car.' }, { de: 'Wie ist deine Telefonnummer?', en: 'What is your phone number?' }, { de: 'Ich suche meinen Schlüssel.', en: 'I am looking for my key.' }],
        tip: 'The ending matches the noun after it, not the owner: meine Mutter is -e because Mutter is feminine, not because you are female.',
        mistakes: ['Do not say mein Mutter; feminine nouns need meine Mutter.', 'Do not confuse ihr (her/their) with Ihr (your, formal); only the formal one is capitalized.'],
        practice: ['Introduce your family with mein/meine plus a noun.', 'Make three accusative sentences with meinen, deinen, and seinen.'],
      },
      {
        id: 'a1-past-tense-imperfect',
        title: 'Simple Past: war, hatte, gab',
        focus: 'war, hatte, gab',
        explanation: 'The most useful early simple-past verbs are sein, haben, and es gibt. These forms are short, common, and let you talk about states in the past without building the full Perfekt yet.',
        rules: ['sein in simple past: ich war, du warst, er/sie/es war, wir waren.', 'haben in simple past: ich hatte, du hattest, er/sie/es hatte, wir hatten.', 'Time adverbs like nie, selten, manchmal, oft, and immer make past sentences more natural.'],
        examples: [{ de: 'Ich war krank.', en: 'I was sick.' }, { de: 'Hattest du gestern Spaß?', en: 'Did you have fun yesterday?' }, { de: 'Es gab ein Problem.', en: 'There was a problem.' }],
        tip: 'For A1 speaking, war and hatte are worth memorizing as whole words, not building from a rule.',
        mistakes: ['Do not use Perfekt every time with sein and haben; ich war and ich hatte are very natural.', 'Do not forget the question order: Hattest du...?'],
        practice: ['Say three things about yesterday with war, hatte, and gab.', 'Add nie, selten, manchmal, oft, or immer to three past sentences.'],
      },
      {
        id: 'a1-articles-nouns-dative',
        title: 'Articles And Nouns: Dative',
        focus: 'indirect object and dative articles',
        explanation: 'Dative is the case for many indirect objects and for many prepositions. It is the first case where several articles visibly change, so it needs slow, repeated practice in real chunks.',
        rules: ['Definite articles: dem Mann, der Frau, dem Kind, den Kindern.', 'Indefinite articles: einem Mann, einer Frau, einem Kind, keinen Kindern.', 'Dative personal pronouns: mir, dir, ihm, ihr, ihm, uns, euch, ihnen/Ihnen.', 'Plural dative often adds -n to the noun if the plural does not already end in -n or -s.'],
        examples: [{ de: 'Ich helfe dem Mann.', en: 'I help the man.' }, { de: 'Kannst du mir helfen?', en: 'Can you help me?' }, { de: 'Sie schreibt einer Freundin.', en: 'She writes to a friend.' }, { de: 'Ich fahre mit den Kindern.', en: 'I travel with the children.' }],
        tip: 'Learn dative in chunks with prepositions: mit dem, bei der, zu den.',
        mistakes: ['Do not use den for every dative noun; dem is masculine and neuter singular.', 'Do not forget the plural dative -n when it is needed.'],
        practice: ['Make sentences with helfen, schreiben, danken, and mit.', 'Build a mini table for der Termin, die Karte, das Formular, die Kinder.'],
      },
      {
        id: 'a1-building-good-sentences',
        title: 'Building (Good) Sentences',
        focus: 'SVO, verb position, TE-KA-MO-LO',
        explanation: 'This topic revisits word order after you know more cases and pronouns. It combines S-V-O, question order, pronoun order in questions, and TE-KA-MO-LO for arranging time, cause, manner, and place.',
        rules: ['Short neutral statements often use subject + verb + object.', 'The verb stays position 2 even when the first idea changes.', 'TE-KA-MO-LO is a helpful order: time, cause, manner, location.'],
        examples: [{ de: 'Ich bin Lehrerin.', en: 'I am a teacher.' }, { de: 'Gefällt er dir?', en: 'Do you like it?' }, { de: 'Petra war heute wegen des Wetters zu spät im Büro.', en: 'Petra was late at the office today because of the weather.' }],
        tip: 'Use TE-KA-MO-LO when a sentence has several extra details and you need a reliable order.',
        mistakes: ['Do not move pronouns randomly in questions.', 'Do not let a long first phrase push the verb away from position 2.'],
        practice: ['Write one sentence with time, reason, manner, and place.', 'Fix three sentences where the verb is not in position 2.'],
      },
      {
        id: 'a1-imperative',
        title: 'Imperative',
        focus: 'commands and advice',
        explanation: 'Imperative is for direct orders, instructions, or advice. Learn the core du, ihr, and formal Sie forms, then add the extra care needed for separable verbs.',
        rules: ['Informal singular often uses the verb stem: Sag! Komm!', 'Informal plural uses the ihr-form without ihr: Sagt! Kommt!', 'Formal imperative uses the infinitive plus Sie: Sagen Sie! Kommen Sie!'],
        examples: [{ de: 'Sag das bitte noch einmal.', en: 'Please say that again.' }, { de: 'Sagen Sie mir bitte Bescheid.', en: 'Please let me know.' }, { de: 'Nimm deinen Ausweis mit.', en: 'Take your ID with you.' }],
        tip: 'With separable verbs, the prefix still goes to the end: Nimm mit, ruf an, füll aus.',
        mistakes: ['Do not use the infinitive alone for du commands in normal speech.', 'Do not forget the prefix in separable imperative forms.'],
        practice: ['Make du, ihr, and Sie commands for sagen, kommen, warten, mitbringen.', 'Write three polite instructions for an appointment.'],
      },
      {
        id: 'a1-prepositions',
        title: 'Prepositions',
        focus: 'accusative and dative prepositions',
        explanation: 'Prepositions decide the case of the noun after them. At A1, separate them into accusative and dative groups; two-way prepositions come at A2.',
        rules: ['Accusative prepositions: bis, durch, für, gegen, ohne, um.', 'Dative prepositions: aus, bei, mit, seit, nach, von, zu, gegenüber.', 'Some nouns appear without an article, so the case may not be visible every time.'],
        examples: [{ de: 'Maria kann ohne Handy nicht leben.', en: 'Maria cannot live without a phone.' }, { de: 'Kommst du von der Arbeit?', en: 'Are you coming from work?' }, { de: 'Ich fahre mit dem Bus.', en: 'I travel by bus.' }],
        tip: 'Memorize prepositions by case, not by English translation only.',
        mistakes: ['Do not use accusative after mit; say mit dem Bus.', 'Do not treat Wechselpräpositionen as A1 fixed-case prepositions.'],
        practice: ['Sort ten prepositions into accusative and dative.', 'Make one daily-life sentence with ohne, für, mit, seit, von, and zu.'],
      },
      {
        id: 'a1-past-tense-perfect',
        title: 'Spoken Past: Perfekt',
        focus: 'haben/sein + Partizip II',
        explanation: 'Perfekt is the main spoken past tense for everyday German. It builds a verb bracket with haben or sein near the front and the past participle at the end.',
        rules: ['Most verbs use haben: Ich habe den Film gesehen.', 'Movement or change-of-state verbs often use sein: Ich bin gekommen.', 'Weak participles usually use ge- + stem + -t; strong verbs often use ge- + changed stem + -en.'],
        examples: [{ de: 'Ich habe den Film gesehen.', en: 'I watched the film.' }, { de: 'Hast du den Film gesehen?', en: 'Did you watch the film?' }, { de: 'Ich bin gestern nach Hause gegangen.', en: 'I went home yesterday.' }],
        tip: 'The participle does not change by person, so the main work is choosing haben/sein and learning the participle form.',
        mistakes: ['Do not put the participle in the middle.', 'Do not use haben with common movement verbs like gehen and kommen.'],
        practice: ['Tell three things you did yesterday with Perfekt.', 'Sort kommen, kaufen, bezahlen, gehen, bleiben, sehen into haben/sein groups.'],
      },
      {
        id: 'a1-connecting-sentences',
        title: 'Connecting Sentences',
        focus: 'und, oder, aber, sondern, denn',
        explanation: 'These connectors join main sentences and keep normal main-clause word order, so they are useful before A2 subordinate clauses arrive.',
        rules: ['und and oder connect equal ideas and often allow the repeated subject to disappear.', 'sondern follows a negative first idea and gives the correction.', 'denn gives a reason but does not move the verb.'],
        examples: [{ de: 'Pia ist Verkäuferin und wohnt in Berlin.', en: 'Pia is a saleswoman and lives in Berlin.' }, { de: 'Ich habe keine Zeit am Montag, sondern am Mittwoch.', en: 'I do not have time on Monday, but on Wednesday instead.' }, { de: 'Sie hat keine Zeit, denn sie arbeitet.', en: 'She has no time because she is working.' }],
        tip: 'These are main-sentence connectors. The verb order after them stays familiar.',
        mistakes: ['Do not use sondern unless the first idea is negative.', 'Do not send the verb to the end after denn.'],
        practice: ['Connect the same two sentences with und, aber, and denn.', 'Write three corrected statements with nicht/kein plus sondern.'],
      },
    ],
  },
  {
    id: 'a2',
    level: 'A2',
    title: 'A2 Grammar',
    subtitle: 'Connections: comparisons, double objects, subordinate clauses, two-way prepositions, Genitiv, pronouns, and stronger past forms.',
    outcome: 'You can compare options, connect reasons and conditions, manage dative/accusative together, and read more formal German.',
    lessons: [
      {
        id: 'a2-comparative-form',
        title: 'Comparative Form',
        focus: 'adjective + -er, als',
        explanation: 'The comparative compares differences. Start with adjective plus -er, then add irregular forms, quantity words like mehr and weniger, and the sentence pattern with als.',
        rules: ['Most comparatives add -er: laut -> lauter, grün -> grüner.', 'Use als for unequal comparison: schneller als.', 'Some words are irregular or add Umlaut: gut -> besser, arm -> ärmer.'],
        examples: [{ de: 'Der Zug ist schneller als der Bus.', en: 'The train is faster than the bus.' }, { de: 'Am Ende des Monats hat er weniger Geld.', en: 'At the end of the month he has less money.' }, { de: 'Er spricht besser Deutsch als seine Schwester.', en: 'He speaks better German than his sister.' }],
        tip: 'Memorize gut -> besser and viel -> mehr early; they appear constantly in daily speech.',
        mistakes: ['Do not use wie for unequal comparison.', 'Do not add -er to every word blindly; some forms are irregular.'],
        practice: ['Compare two apartments, two appointments, and two transport options.', 'Make five sentences using besser, schneller, günstiger, mehr, and weniger.'],
      },
      {
        id: 'a2-superlative',
        title: 'Superlative',
        focus: 'am -sten, der/die/das -ste',
        explanation: 'The superlative gives the highest degree. Separate the adverbial form with am from the adjective-before-noun form, where normal adjective declension matters.',
        rules: ['Use am + adjective + -sten after the verb: am schnellsten.', 'Before a noun, use der/die/das plus a declined adjective: der schnellste Läufer.', 'For equal comparison, use so/genauso + adjective + wie.'],
        examples: [{ de: 'Er rennt am schnellsten.', en: 'He runs the fastest.' }, { de: 'Er ist der schnellste Läufer in seiner Klasse.', en: 'He is the fastest runner in his class.' }, { de: 'Er spricht so gut Deutsch wie ich.', en: 'He speaks German as well as I do.' }],
        tip: 'Use am when no noun follows. Drop am when the superlative stands before a noun.',
        mistakes: ['Do not say der am schnellste Läufer.', 'Do not use als for equal comparison; use so ... wie.'],
        practice: ['Describe the fastest, cheapest, and best option.', 'Write three equal comparisons with so ... wie.'],
      },
      {
        id: 'a2-dative-accusative',
        title: 'Dative And Accusative',
        focus: 'two objects in one sentence',
        explanation: 'A2 combines dative and accusative in one sentence. The common pattern is dative person before accusative thing, but pronouns change the order, so learners need both the basic pattern and the pronoun exception.',
        rules: ['Common noun order: subject + verb + dative object + accusative object.', 'If the accusative object is a pronoun and the dative is not, the accusative pronoun often comes first.', 'When both objects are pronouns, accusative comes before dative.'],
        examples: [{ de: 'Ich schicke dem Professor einen Brief.', en: 'I send the professor a letter.' }, { de: 'Sie erklärt dem Kunden den Vertrag.', en: 'She explains the contract to the customer.' }, { de: 'Ich gebe ihn dir.', en: 'I give it to you.' }],
        tip: 'Learn the everyday noun pattern first; then drill pronoun swaps separately.',
        mistakes: ['Do not assume dative is always a living person.', 'Do not keep noun order when both objects become pronouns.'],
        practice: ['Make sentences with geben, schicken, zeigen, and erklären.', 'Replace one object, then both objects, with pronouns.'],
      },
      {
        id: 'a2-modalverbs-imperfect',
        title: 'Modal Verbs In Simple Past',
        focus: 'konnte, musste, durfte, wollte, sollte',
        explanation: 'The simple past of modal verbs is common and useful because the main verb stays as an infinitive at the end. This lets you explain what you could, had to, wanted to, or were allowed to do.',
        rules: ['Pattern: subject + modal in simple past + rest + infinitive.', 'möchten uses wollte in the plain past.', 'Common forms: konnte, musste, durfte, wollte, sollte.'],
        examples: [{ de: 'Er durfte als Kind nie Fahrrad fahren.', en: 'He was never allowed to ride a bike as a child.' }, { de: 'Wir mussten immer um 7 Uhr aufstehen.', en: 'We always had to get up at 7.' }, { de: 'Ich konnte gestern nicht kommen.', en: 'I could not come yesterday.' }],
        tip: 'These forms are more natural than building Perfekt with modals in many everyday stories.',
        mistakes: ['Do not conjugate the final infinitive.', 'Do not use möchte in past; use wollte.'],
        practice: ['Tell why you missed something using konnte, musste, and durfte.', 'Write three childhood sentences with als Kind.'],
      },
      {
        id: 'a2-connecting-sentences-2',
        title: 'Connecting Sentences With weil',
        focus: 'weil and subordinate clauses',
        explanation: 'A2 connectors get harder because some connectors turn the second idea into a subordinate clause. With weil, the conjugated verb moves to the end; when that subordinate clause comes first, the main verb follows the comma.',
        rules: ['weil introduces a reason clause with verb-final order.', 'A fronted subordinate clause counts as position 1, so the main verb comes right after the comma.', 'Comma placement helps you see the boundary between clauses.'],
        examples: [{ de: 'Peter isst selten Steak, weil es teuer ist.', en: 'Peter rarely eats steak because it is expensive.' }, { de: 'Ich bleibe zu Hause, weil ich krank bin.', en: 'I am staying home because I am sick.' }, { de: 'Weil ich keine Zeit habe, kann ich leider nicht kommen.', en: 'Because I have no time, unfortunately I cannot come.' }],
        tip: 'After weil, send the verb home to the end.',
        mistakes: ['Do not write weil ich bin krank.', 'Do not forget inversion after a fronted subordinate clause.'],
        practice: ['Connect five pairs of sentences with weil.', 'Move each weil-clause to the front and fix the main clause.'],
      },
      {
        id: 'a2-wenn-falls-dann',
        title: 'Wenn/Falls..., (dann)...',
        focus: 'conditions and consequences',
        explanation: 'Conditions need a subordinate clause. Wenn or falls gives the condition, the optional dann points to the consequence, and the verb in the condition clause moves to the end.',
        rules: ['Wenn/Falls + condition with verb-final order.', 'dann is optional in the consequence clause.', 'If the wenn-clause comes second, the first clause uses normal main-clause order.'],
        examples: [{ de: 'Wenn es morgen regnet, bleiben wir zu Hause.', en: 'If it rains tomorrow, we will stay home.' }, { de: 'Wir bleiben zu Hause, wenn es morgen regnet.', en: 'We will stay home if it rains tomorrow.' }, { de: 'Falls ich später komme, rufe ich an.', en: 'If I come later, I will call.' }],
        tip: 'Use falls when the condition sounds a bit less certain than normal wenn.',
        mistakes: ['Do not put dann before the condition clause.', 'Do not forget verb-final order inside the wenn/falls clause.'],
        practice: ['Write three real conditions for appointments, weather, and work.', 'Swap the order of each sentence and adjust word order.'],
      },
      {
        id: 'a2-dass-sentences',
        title: 'Subordinate Clauses With dass',
        focus: 'that-clauses',
        explanation: 'Dass lets you report thoughts, opinions, information, and feelings. It is another subordinate clause, so the conjugated verb goes to the end, including with modal verbs and Perfekt.',
        rules: ['dass means that in report/thought clauses.', 'The verb goes to the end: Ich finde, dass er nett ist.', 'With a modal, the modal goes to the end: dass du kommen kannst.'],
        examples: [{ de: 'Ich finde, dass er nett ist.', en: 'I think that he is nice.' }, { de: 'Ich denke, dass es morgen regnet.', en: 'I think that it will rain tomorrow.' }, { de: 'Es ist schade, dass du nicht kommen kannst.', en: 'It is a pity that you cannot come.' }],
        tip: 'Common starters are ich finde, ich denke, ich glaube, ich hoffe, and es ist schade.',
        mistakes: ['Do not keep main-clause order after dass.', 'Do not confuse dass with das as article or demonstrative pronoun.'],
        practice: ['Report five opinions with Ich finde, dass...', 'Write three office/email sentences with Ich hoffe, dass...'],
      },
      {
        id: 'a2-two-way-prepositions',
        title: 'Two-Way Prepositions',
        focus: 'where vs where to',
        explanation: 'Two-way prepositions can use accusative or dative. The practical distinction is direction toward a target versus location at a place. This is why in den Park and im Park mean different things.',
        rules: ['Use accusative for direction/change of location: wohin?', 'Use dative for location/state: wo?', 'Common two-way prepositions: in, an, auf, unter, über, vor, hinter, neben, zwischen.'],
        examples: [{ de: 'Ich gehe in den Supermarkt.', en: 'I am going into the supermarket.' }, { de: 'Ich bin im Supermarkt.', en: 'I am in the supermarket.' }, { de: 'Der Brief liegt auf dem Tisch.', en: 'The letter is lying on the table.' }],
        tip: 'Use the arrow test: arrow into a target means accusative; no arrow means dative.',
        mistakes: ['Not every movement uses accusative; walking around inside a park is im Park.', 'Do not confuse legen with liegen or stellen with stehen.'],
        practice: ['Describe five objects in your room with dative.', 'Move those objects and describe the action with accusative.'],
      },
      {
        id: 'a2-konjunktiv-ii',
        title: 'Konjunktiv II',
        focus: 'wishes, unreal situations, polite questions',
        explanation: 'Konjunktiv II is used for unreal situations, wishes, advice, and polite questions. Learn both würde plus infinitive and special forms like hätte, wäre, and könnte.',
        rules: ['Present pattern: würde + infinitive or a special Konjunktiv II verb form.', 'Polite questions often use würden or könnten.', 'Past unreal situations use hätte/wäre + Partizip II.'],
        examples: [{ de: 'Ich würde nie zu spät kommen.', en: 'I would never come late.' }, { de: 'Ich hätte gerne einen Hund.', en: 'I would like to have a dog.' }, { de: 'Könntest du mir bitte helfen?', en: 'Could you please help me?' }],
        tip: 'For daily use, master hätte, wäre, könnte, and würde gern first.',
        mistakes: ['Do not overuse würde when a common special form exists.', 'Do not forget this grammar often describes something not real.'],
        practice: ['Make three polite requests softer with könnten or würden.', 'Write two unreal if-sentences with hätte and wäre.'],
      },
      {
        id: 'a2-futur-i',
        title: 'Futur I',
        focus: 'werden + infinitive',
        explanation: 'Futur I uses werden plus an infinitive at the end. In everyday speech, present tense plus a time word often handles the future, but Futur I is useful for predictions, promises, and formal statements.',
        rules: ['Pattern: subject + werden + rest + infinitive.', 'Present tense with a future time word is often enough: Morgen komme ich.', 'Use Futur I when the future meaning needs emphasis or sounds like a forecast.'],
        examples: [{ de: 'Ich werde morgen anrufen.', en: 'I will call tomorrow.' }, { de: 'Wir werden die Unterlagen prüfen.', en: 'We will check the documents.' }, { de: 'Es wird wahrscheinlich regnen.', en: 'It will probably rain.' }],
        tip: 'Think of werden as the front verb and the real action as the end verb.',
        mistakes: ['Do not conjugate the final infinitive.', 'Do not use Futur I just because English uses will; German often uses present tense.'],
        practice: ['Write three promises with ich werde...', 'Rewrite three future sentences using present tense plus a time word.'],
      },
      {
        id: 'a2-genitiv',
        title: 'Genitive Case',
        focus: 'possession and formal written German',
        explanation: 'Genitiv is often learned last even though it is the second case. It marks possession and other formal relationships, and it appears often in written German, signs, contracts, and official texts.',
        rules: ['Masculine/neuter definite forms: des + noun ending -s or -es.', 'Feminine/plural definite form: der.', 'Ask with wessen? for whose.'],
        examples: [{ de: 'Das ist das Buch der Lehrerin.', en: "That is the teacher's book." }, { de: 'Das ist das Buch des Lehrers.', en: "That is the male teacher's book." }, { de: 'Wessen Kaffee ist das?', en: 'Whose coffee is that?' }],
        tip: 'For speaking, von + dative is common; for reading, recognizing genitive is essential.',
        mistakes: ['Do not mistake feminine genitive der for dative automatically.', 'Do not forget the -s/-es ending on many masculine and neuter nouns.'],
        practice: ['Find three genitive phrases in a formal text.', 'Rewrite two genitive phrases with von + dative.'],
      },
      {
        id: 'a2-pronouns',
        title: 'Pronouns',
        focus: 'substitution and declension',
        explanation: 'Pronouns substitute nouns or accompany them. Personal, possessive, reflexive, relative, interrogative, demonstrative, and indefinite pronouns each have different jobs and forms.',
        rules: ['Some pronouns do not decline, such as etwas and nichts.', 'jemand, niemand, jeder, ein-, and kein- can change form by case and gender.', 'man changes in object cases: einem in dative and einen in accusative.'],
        examples: [{ de: 'Ich habe am Wochenende nichts gemacht.', en: 'I did nothing on the weekend.' }, { de: 'Kennst du jemanden hier?', en: 'Do you know somebody here?' }, { de: 'Ich habe keinen.', en: 'I do not have one.' }],
        tip: 'Ask whether the word replaces a noun or stands with a noun; that tells you how to read it.',
        mistakes: ['Do not assume every pronoun is fixed and undeclinable.', 'Do not confuse einer as a person-substitute with the article eine.'],
        practice: ['Replace nouns with pronouns in five everyday sentences.', 'Make sentences with jemand, niemand, nichts, einer, and keiner.'],
      },
      {
        id: 'a2-reflective-verbs',
        title: 'Reflexive Verbs',
        focus: 'sich verbs',
        explanation: 'Reflexive verbs use a pronoun that points back to the subject, such as mich, dich, sich, uns, and euch. Some are always reflexive; others change meaning with the pronoun.',
        rules: ['Learn reflexive verbs with sich in the dictionary form.', 'Accusative reflexive: ich melde mich an.', 'Dative reflexive appears when there is another direct object: Ich notiere mir den Termin.'],
        examples: [{ de: 'Ich melde mich online an.', en: 'I register online.' }, { de: 'Sie freut sich auf den Urlaub.', en: 'She is looking forward to the holiday.' }, { de: 'Ich notiere mir die Adresse.', en: 'I write down the address for myself.' }],
        tip: 'Learn the whole pattern, not only the verb: sich freuen auf + accusative, sich kümmern um + accusative.',
        mistakes: ['Do not translate the reflexive pronoun literally every time.', 'Do not use mich when dative mir is required by the pattern.'],
        practice: ['Conjugate sich anmelden for ich, du, er, wir, Sie.', 'Write two sentences with mich and two with mir.'],
      },
      {
        id: 'a2-adjective-declinations',
        title: 'Adjective Declinations',
        focus: 'endings before nouns',
        explanation: 'Adjectives before nouns need endings. The ending depends on article type, gender, number, and case. At A2, the fastest path is to master frequent chunks before memorizing every table.',
        rules: ['After der/die/das in nominative: der neue Vertrag, die neue Karte, das neue Formular.', 'After ein/eine: ein neuer Vertrag, eine neue Karte, ein neues Formular.', 'Accusative masculine uses -en: einen neuen Termin.'],
        examples: [{ de: 'Ich brauche einen neuen Termin.', en: 'I need a new appointment.' }, { de: 'Die neue Adresse ist richtig.', en: 'The new address is correct.' }, { de: 'Haben Sie ein anderes Formular?', en: 'Do you have another form?' }],
        tip: 'When the article does not show enough information, the adjective ending often carries it.',
        mistakes: ['Do not say ein neue Termin.', 'Do not forget -en in accusative masculine.'],
        practice: ['Build phrases with neu for der Termin, die Karte, das Formular, die Unterlagen.', 'Write five real requests using adjective + noun.'],
      },
      {
        id: 'a2-n-declination',
        title: 'N-Declination',
        focus: 'weak masculine nouns',
        explanation: 'N-declination affects a group of masculine nouns that add -n or -en outside nominative singular. Many are people or animals, so this topic matters in everyday sentences about people.',
        rules: ['Weak masculine nouns add -n/-en in accusative, dative, and genitive singular.', 'Common examples: der Junge, der Kunde, der Kollege, der Nachbar.', 'Some add -ens in genitive, such as der Name -> des Namens.'],
        examples: [{ de: 'Ich frage den Kollegen.', en: 'I ask the colleague.' }, { de: 'Ich helfe dem Nachbarn.', en: 'I help the neighbor.' }, { de: 'Der Name des Kunden fehlt.', en: 'The customer name is missing.' }],
        tip: 'If a masculine person noun ends in -e, check whether it belongs to this group.',
        mistakes: ['Do not say den Kollege; say den Kollegen.', 'Do not apply N-declination to all masculine nouns.'],
        practice: ['Make accusative and dative sentences with Kunde, Kollege, Nachbar, Junge.', 'Find weak masculine nouns in a dictionary and write their forms.'],
      },
      {
        id: 'a2-prepositional-objects',
        title: 'Prepositional Objects',
        focus: 'verb + preposition patterns',
        explanation: 'Some verbs need a preposition as part of their pattern. Learn these patterns one by one because the preposition and case are not always predictable from English.',
        rules: ['Learn verb + preposition + case as one unit.', 'warten auf + accusative means to wait for something or someone.', 'The same verb can have different preposition patterns with different meanings.'],
        examples: [{ de: 'Ich warte auf dich.', en: 'I am waiting for you.' }, { de: 'Ich warte auf den Bus.', en: 'I am waiting for the bus.' }, { de: 'Ich warte mit dem Mittagessen.', en: 'I am holding off on lunch.' }],
        tip: 'Make vocabulary cards that include the preposition and case, not just the verb.',
        mistakes: ['Do not translate English prepositions directly.', 'Do not forget that the preposition chooses the case.'],
        practice: ['Create ten cards for verb + preposition + case patterns.', 'Use warten auf, sprechen über, sich interessieren für, and helfen bei.'],
      },
      {
        id: 'a2-imperfect-tense',
        title: 'Simple Past: Weak, Strong, And Mixed Verbs',
        focus: 'weak, strong, and mixed Präteritum',
        explanation: 'This topic expands Präteritum beyond war, hatte, gab, and modal verbs. Sort verbs into weak, strong, and mixed groups so you can recognize written past forms and tell simple stories.',
        rules: ['Weak verbs add -te endings: kaufte, kauftest, kaufte, kauften.', 'Strong verbs often change the stem vowel: gehen -> ging.', 'Mixed verbs combine a stem change with weak-style endings: wissen -> wusste.'],
        examples: [{ de: 'Er kaufte ein Geschenk.', en: 'He bought a present.' }, { de: 'Er ging nach Hause.', en: 'He went home.' }, { de: 'Er wusste nicht, wann das Meeting begann.', en: 'He did not know when the meeting started.' }],
        tip: 'For speaking, Perfekt is often enough; for reading, Präteritum recognition is important.',
        mistakes: ['Do not expect every strong verb to follow the weak -te pattern.', 'Do not use Präteritum heavily in everyday speech unless the verb is common in that form.'],
        practice: ['Sort ten verbs into weak, strong, and mixed.', 'Rewrite a short Perfekt story with selected Präteritum forms.'],
      },
    ],
  },
  {
    id: 'b1',
    level: 'B1',
    title: 'B1 Grammar',
    subtitle: 'Independent use: complex clauses, passive, reported information, formal written structures, and connected arguments.',
    outcome: 'You can express opinions, use polite and unreal forms, understand official grammar, and connect longer spoken or written ideas.',
    lessons: [
      {
        id: 'b1-konjunktiv-ii-deepening',
        title: 'Konjunktiv II Deepening',
        focus: 'polite, unreal, and past unreal forms',
        explanation: 'B1 uses Konjunktiv II more flexibly than A2. You need it for polite requests, wishes, advice, unreal conditions, and past situations that did not happen.',
        rules: ['Use hätte, wäre, könnte, and würde gern for practical polite speech.', 'Unreal present often uses wenn + Konjunktiv II plus würde + infinitive.', 'Unreal past uses hätte/wäre + Partizip II.'],
        examples: [{ de: 'Könnten Sie mir bitte helfen?', en: 'Could you please help me?' }, { de: 'Wenn ich mehr Zeit hätte, würde ich mehr üben.', en: 'If I had more time, I would practice more.' }, { de: 'Ich wäre früher gekommen, wenn der Zug pünktlich gewesen wäre.', en: 'I would have come earlier if the train had been on time.' }],
        tip: 'Use the shortest natural form: könnte is better than würde können.',
        mistakes: ['Do not make every clause with würde when a common special form exists.', 'Do not use unreal grammar for real future plans.'],
        practice: ['Rewrite five direct requests politely.', 'Write three unreal if-sentences about time, money, and learning.'],
      },
      {
        id: 'b1-passive',
        title: 'Passive Voice',
        focus: 'werden + Partizip II',
        explanation: 'Passive focuses on the action or process, not the person doing it. This is especially useful for official German, where documents are checked, requests are processed, and payments are booked.',
        rules: ['Present passive: werden + Partizip II.', 'Past passive: wurde/wurden + Partizip II.', 'Add an agent with von or durch only when it matters.'],
        examples: [{ de: 'Der Antrag wird geprüft.', en: 'The application is being checked.' }, { de: 'Die Unterlagen wurden geschickt.', en: 'The documents were sent.' }, { de: 'Die Rechnung wird automatisch bezahlt.', en: 'The bill is paid automatically.' }],
        tip: 'If the sentence cares more about the process than the person, passive may sound natural.',
        mistakes: ['Do not confuse passive werden with future werden; passive needs a participle.', 'Do not move the participle away from the end.'],
        practice: ['Turn five active official sentences into passive.', 'Find passive sentences in a letter or email.'],
      },
      {
        id: 'b1-temporal-clauses',
        title: 'Temporal Clauses',
        focus: 'als, wenn, bevor, nachdem, seitdem',
        explanation: 'B1 stories and procedures need time clauses. These clauses use subordinate word order and help you explain what happened once, what happens repeatedly, and which step comes before or after another.',
        rules: ['Use als for one-time past events.', 'Use wenn for repeated events or future conditions.', 'Use bevor and nachdem to show sequence.'],
        examples: [{ de: 'Als ich angekommen bin, war das Büro geschlossen.', en: 'When I arrived, the office was closed.' }, { de: 'Bevor ich den Antrag schicke, prüfe ich die Unterlagen.', en: 'Before I send the application, I check the documents.' }, { de: 'Seitdem ich hier wohne, lerne ich jeden Tag Deutsch.', en: 'Since moving here, I have been learning German every day.' }],
        tip: 'The first question is whether the event happened once in the past or repeats.',
        mistakes: ['Do not use als for future events.', 'Do not forget inversion when the time clause comes first.'],
        practice: ['Tell your arrival story with als, seitdem, and nachdem.', 'Describe a form process with bevor and nachdem.'],
      },
      {
        id: 'b1-relative-clauses-cases',
        title: 'Relative Clauses And Cases',
        focus: 'der, die, das, den, dem',
        explanation: 'Relative clauses describe a noun without starting a new sentence. The relative pronoun matches the noun in gender and number, but its case comes from its job inside the relative clause.',
        rules: ['The relative-clause verb goes to the end.', 'Choose gender and number from the noun being described.', 'Choose nominative, accusative, or dative from the pronoun job inside the clause.'],
        examples: [{ de: 'Der Mann, der dort wartet, ist mein Nachbar.', en: 'The man who is waiting there is my neighbor.' }, { de: 'Das Formular, das ich brauche, ist online.', en: 'The form that I need is online.' }, { de: 'Die Kollegin, der ich geschrieben habe, antwortet morgen.', en: 'The colleague whom I wrote to will answer tomorrow.' }],
        tip: 'Solve relative pronouns in two steps: noun gender first, clause case second.',
        mistakes: ['Do not choose the case from the main sentence.', 'Do not leave the relative-clause verb in position 2.'],
        practice: ['Combine three sentence pairs with relative clauses.', 'Underline the relative pronoun and label its case.'],
      },
      {
        id: 'b1-purpose-clauses',
        title: 'Purpose Clauses',
        focus: 'um ... zu and damit',
        explanation: 'Purpose clauses explain the goal of an action. Use um ... zu when both actions have the same subject; use damit when the subjects are different or must be stated clearly.',
        rules: ['Same subject: um + details + zu + infinitive.', 'Different subjects: damit + subordinate clause with verb-final order.', 'With separable verbs, zu goes inside the verb: auszufüllen.'],
        examples: [{ de: 'Ich lerne Deutsch, um im Alltag sicherer zu sprechen.', en: 'I learn German in order to speak more confidently in daily life.' }, { de: 'Ich schicke Ihnen den Link, damit Sie das Formular finden.', en: 'I am sending you the link so that you can find the form.' }, { de: 'Sie ruft an, um den Termin abzusagen.', en: 'She calls to cancel the appointment.' }],
        tip: 'Check whether the subject stays the same before choosing um ... zu.',
        mistakes: ['Do not use um ... zu when the two actions have different subjects.', 'Do not put zu before a separable prefix.'],
        practice: ['Write three personal goals with um ... zu.', 'Rewrite two different-subject goals with damit.'],
      },
      {
        id: 'b1-infinitive-clauses',
        title: 'Extended Infinitive Clauses',
        focus: 'ohne zu, statt zu, zu + infinitive',
        explanation: 'Extended infinitive clauses make sentences compact. They are common after verbs, nouns, adjectives, and with ohne or statt when the subject of both actions is the same.',
        rules: ['Use zu + infinitive after expressions such as versuchen, vergessen, and die Möglichkeit haben.', 'ohne ... zu means without doing something.', 'statt ... zu means instead of doing something.'],
        examples: [{ de: 'Ich versuche, den Antrag heute auszufüllen.', en: 'I am trying to fill out the application today.' }, { de: 'Er ging, ohne sich zu verabschieden.', en: 'He left without saying goodbye.' }, { de: 'Sie schrieb eine E-Mail, statt anzurufen.', en: 'She wrote an email instead of calling.' }],
        tip: 'Use an infinitive clause only when the understood subject is the same.',
        mistakes: ['Do not use zu after modal verbs.', 'Do not forget the comma before extended infinitive groups.'],
        practice: ['Make sentences with versuchen, ohne, and statt.', 'Change two modal sentences into expressions with zu.'],
      },
      {
        id: 'b1-passive-modal-verbs',
        title: 'Passive With Modal Verbs',
        focus: 'modal + Partizip II + werden',
        explanation: 'Passive and modal verbs often appear together in instructions and official texts. The modal verb is conjugated in position 2, while the participle and werden form the verb group at the end.',
        rules: ['Present pattern: modal verb + Partizip II + werden.', 'The action receiver stays the grammatical subject.', 'In a subordinate clause, the whole verb group moves to the end.'],
        examples: [{ de: 'Der Antrag muss online gestellt werden.', en: 'The application must be submitted online.' }, { de: 'Die Rechnung kann später bezahlt werden.', en: 'The invoice can be paid later.' }, { de: 'Die Unterlagen dürfen nicht kopiert werden.', en: 'The documents may not be copied.' }],
        tip: 'Read the final pair first: geprüft werden, bezahlt werden, geschickt werden.',
        mistakes: ['Do not omit werden at the end.', 'Do not conjugate the participle.'],
        practice: ['Turn five instructions into passive with müssen or können.', 'Find the modal, participle, and werden in three official sentences.'],
      },
      {
        id: 'b1-paired-connectors',
        title: 'Paired Connectors',
        focus: 'entweder/oder, weder/noch, sowohl/als auch',
        explanation: 'Paired connectors organize alternatives, double negatives, additions, and contrasts. They connect matching sentence parts and make B1 speaking and writing more structured.',
        rules: ['entweder ... oder presents alternatives.', 'weder ... noch rejects both alternatives.', 'sowohl ... als auch adds two positive elements; nicht nur ... sondern auch adds emphasis.'],
        examples: [{ de: 'Wir können entweder anrufen oder eine E-Mail schreiben.', en: 'We can either call or write an email.' }, { de: 'Ich habe weder Zeit noch Geld.', en: 'I have neither time nor money.' }, { de: 'Der Kurs ist sowohl praktisch als auch interessant.', en: 'The course is both practical and interesting.' }],
        tip: 'Connect grammatically equal pieces: noun with noun, clause with clause, or infinitive with infinitive.',
        mistakes: ['Do not mix connector pairs.', 'Do not connect sentence parts with different grammatical shapes.'],
        practice: ['Describe three choices with entweder ... oder.', 'Write one sentence with each paired connector.'],
      },
      {
        id: 'b1-genitive-prepositions',
        title: 'Genitive Prepositions',
        focus: 'wegen, trotz, während, innerhalb, außerhalb',
        explanation: 'Several common formal prepositions use genitive. You will meet them in letters, rules, contracts, and news, even when everyday speech sometimes uses dative instead.',
        rules: ['wegen gives a reason, trotz gives a contrast, and während gives a time relationship.', 'Masculine and neuter nouns often add -s or -es in genitive.', 'innerhalb and außerhalb describe limits or boundaries.'],
        examples: [{ de: 'Wegen des Wetters fällt der Termin aus.', en: 'The appointment is cancelled because of the weather.' }, { de: 'Trotz des Regens kam sie pünktlich an.', en: 'Despite the rain, she arrived on time.' }, { de: 'Innerhalb einer Woche erhalten Sie eine Antwort.', en: 'You will receive an answer within one week.' }],
        tip: 'Learn each preposition with one complete genitive example.',
        mistakes: ['Do not forget the noun ending in des Vertrags or des Jahres.', 'Do not assume every wegen phrase in formal writing uses dative.'],
        practice: ['Make one sentence with wegen, trotz, während, and innerhalb.', 'Rewrite three reason clauses as prepositional phrases.'],
      },
      {
        id: 'b1-noun-verb-combinations',
        title: 'Noun-Verb Combinations',
        focus: 'eine Entscheidung treffen, in Kontakt bleiben',
        explanation: 'German often expresses one idea with a fixed noun and verb combination. These chunks are common in formal communication and can be more natural than translating a single English verb.',
        rules: ['Learn the article, noun, and verb together as one expression.', 'The noun often carries the main meaning while the verb is general.', 'The fixed expression still follows normal case and word-order rules.'],
        examples: [{ de: 'Wir müssen eine Entscheidung treffen.', en: 'We have to make a decision.' }, { de: 'Bitte nehmen Sie mit uns Kontakt auf.', en: 'Please contact us.' }, { de: 'Die neue Regel tritt morgen in Kraft.', en: 'The new rule comes into effect tomorrow.' }],
        tip: 'Store these expressions as complete reusable chunks.',
        mistakes: ['Do not replace the fixed verb with a direct English translation.', 'Do not drop the article when the expression requires one.'],
        practice: ['Collect ten noun-verb combinations from formal texts.', 'Use eine Entscheidung treffen, Kontakt aufnehmen, and in Kraft treten.'],
      },
      {
        id: 'b1-future-assumptions',
        title: 'Future And Assumptions',
        focus: 'werden, wohl, Futur II awareness',
        explanation: 'At B1, werden can express future plans and assumptions. Context and words such as wohl, wahrscheinlich, or bestimmt help show whether the speaker predicts, guesses, or promises.',
        rules: ['Futur I: werden + infinitive.', 'A present-time assumption can also use werden: Er wird jetzt im Büro sein.', 'Futur II expresses a completed future action or past assumption: wird gemacht haben.'],
        examples: [{ de: 'Ich werde Ihnen morgen antworten.', en: 'I will answer you tomorrow.' }, { de: 'Er wird wohl noch im Büro sein.', en: 'He is probably still at the office.' }, { de: 'Sie wird den Brief schon bekommen haben.', en: 'She will probably already have received the letter.' }],
        tip: 'Look for time words and wohl to decide whether werden means future or assumption.',
        mistakes: ['Do not translate every werden sentence as a simple future.', 'Do not forget haben or sein at the end of Futur II.'],
        practice: ['Write two promises and two assumptions with werden.', 'Identify whether five werden sentences express future, passive, or assumption.'],
      },
      {
        id: 'b1-relative-clauses-prepositions',
        title: 'Relative Clauses With Prepositions',
        focus: 'mit dem, auf den, für die',
        explanation: 'B1 relative clauses often include prepositions. The preposition stays before the relative pronoun, and the pronoun case follows the preposition, not the role you might expect from English.',
        rules: ['Preposition + relative pronoun stays together: mit dem, für den, auf die.', 'The preposition decides the case.', 'Use wo-compounds for abstract things when appropriate.'],
        examples: [{ de: 'Das ist die Frau, mit der ich gesprochen habe.', en: 'That is the woman I spoke with.' }, { de: 'Der Kurs, für den ich mich interessiere, beginnt im Juni.', en: 'The course I am interested in starts in June.' }, { de: 'Das ist ein Problem, über das wir sprechen müssen.', en: 'That is a problem we need to talk about.' }],
        tip: 'Keep the preposition glued to the relative pronoun in your mind.',
        mistakes: ['Do not leave the preposition at the end like English.', 'Do not use wo-compounds for people.'],
        practice: ['Combine three sentence pairs using mit dem, für den, and auf die.', 'Write relative clauses about a course, office, appointment, and person.'],
      },
      {
        id: 'b1-da-wo-compounds',
        title: 'da- And wo- Compounds',
        focus: 'darauf, womit, worüber',
        explanation: 'German often replaces preposition plus thing with a da-compound, and asks about things with a wo-compound. These forms are very common with prepositional objects.',
        rules: ['auf das -> darauf, mit dem -> damit, über das -> darüber.', 'Question forms use wo-: worauf, womit, worüber.', 'Add r when the preposition starts with a vowel: darauf, worüber.'],
        examples: [{ de: 'Ich warte darauf.', en: 'I am waiting for that.' }, { de: 'Worauf warten Sie?', en: 'What are you waiting for?' }, { de: 'Damit bin ich nicht einverstanden.', en: 'I do not agree with that.' }],
        tip: 'Use da-/wo-compounds for things and ideas, not usually for people.',
        mistakes: ['Do not say darauf for a person you are waiting for.', 'Do not forget the r before vowel-starting prepositions.'],
        practice: ['Transform auf das, mit dem, über das, für das into da-compounds.', 'Ask three wo-compound questions about forms, payments, and appointments.'],
      },
      {
        id: 'b1-plusquamperfekt',
        title: 'Plusquamperfekt',
        focus: 'past before past',
        explanation: 'Plusquamperfekt describes an action that happened before another past action. It is useful when a story has two past moments and you need the earlier one to be clear.',
        rules: ['haben verbs use hatte + Partizip II.', 'sein verbs use war + Partizip II.', 'Use it with bevor, nachdem, als, or schon when the order matters.'],
        examples: [{ de: 'Ich hatte den Antrag schon geschickt, bevor ich die E-Mail bekommen habe.', en: 'I had already sent the application before I received the email.' }, { de: 'Als ich ankam, war der Arzt schon gegangen.', en: 'When I arrived, the doctor had already left.' }, { de: 'Ich hatte die Rechnung bezahlt, aber das System zeigte sie noch offen.', en: 'I had paid the bill, but the system still showed it as open.' }],
        tip: 'Use Plusquamperfekt only when the earlier past action matters.',
        mistakes: ['Do not use it for every past sentence.', 'Do not use hatte with movement verbs that need war.'],
        practice: ['Explain a misunderstanding with hatte schon...', 'Write three before/after event pairs.'],
      },
      {
        id: 'b1-reported-information',
        title: 'Reported Information',
        focus: 'dass, sollen, laut, Konjunktiv I awareness',
        explanation: 'B1 learners often report what an office, doctor, landlord, or colleague said. Everyday German uses dass and sollen often; more formal texts may use source phrases or Konjunktiv I.',
        rules: ['Use dass to report information.', 'Use sollen when someone instructed you to do something.', 'Use laut + noun to report a written source.'],
        examples: [{ de: 'Die Mitarbeiterin sagt, dass ich eine Kopie brauche.', en: 'The employee says that I need a copy.' }, { de: 'Ich soll das Formular online hochladen.', en: 'I am supposed to upload the form online.' }, { de: 'Laut Brief ist die Zahlung noch offen.', en: 'According to the letter, the payment is still open.' }],
        tip: 'For speaking, dass and sollen solve most reporting needs.',
        mistakes: ['Do not replace every instruction with müssen; sollen often shows that someone told you.', 'Do not forget verb-final order after dass.'],
        practice: ['Report three instructions with Ich soll...', 'Summarize one letter using laut Schreiben.'],
      },
      {
        id: 'b1-participle-adjectives',
        title: 'Participles As Adjectives',
        focus: 'fehlend, bezahlt, geschlossen',
        explanation: 'Participles can describe nouns like adjectives. This appears often in written German, especially in office language: missing documents, paid invoices, closed offices, suitable appointments.',
        rules: ['Partizip I often has active/ongoing meaning: fehlende Unterlagen.', 'Partizip II often has passive/completed meaning: bezahlte Rechnung.', 'Participles take normal adjective endings.'],
        examples: [{ de: 'Die fehlenden Unterlagen muss ich nachreichen.', en: 'I have to submit the missing documents later.' }, { de: 'Die bezahlte Rechnung ist im Anhang.', en: 'The paid invoice is attached.' }, { de: 'Ich suche einen passenden Termin.', en: 'I am looking for a suitable appointment.' }],
        tip: 'If the compact form feels hard, rewrite it as a relative clause first.',
        mistakes: ['Do not forget adjective endings.', 'Do not use gefehlt as a normal adjective for missing documents.'],
        practice: ['Rewrite relative clauses as participle adjectives.', 'Use bezahlt, geschlossen, fehlend, and passend in practical sentences.'],
      },
      {
        id: 'b1-nominal-style',
        title: 'Nominal Style In Official German',
        focus: 'nouns instead of verbs',
        explanation: 'Official German often turns actions into nouns. This can make texts dense, but recognizing endings like -ung, -heit, -keit, and -schaft helps you unpack the meaning.',
        rules: ['-ung often turns a verb into an action/result noun.', '-heit and -keit often turn qualities into nouns.', 'For your own writing, a clear verb sentence is usually easier.'],
        examples: [{ de: 'Die Anmeldung ist nur mit Termin möglich.', en: 'Registration is only possible with an appointment.' }, { de: 'Für die Bearbeitung brauchen wir zwei Wochen.', en: 'We need two weeks for processing.' }, { de: 'Nach der Prüfung erhalten Sie eine Bestätigung.', en: 'After checking, you will receive a confirmation.' }],
        tip: 'When reading, turn the noun back into a verb in your head: Bearbeitung -> jemand bearbeitet etwas.',
        mistakes: ['Do not imitate heavy official style when a clear sentence is better.', 'Remember that most -ung nouns are feminine.'],
        practice: ['Collect five -ung nouns from a letter and convert them to verbs.', 'Rewrite one official sentence in simpler spoken German.'],
      },
      {
        id: 'b1-opinion-argument-structure',
        title: 'Opinion And Argument Structure',
        focus: 'reason, contrast, result',
        explanation: 'B1 communication requires connected opinions. You need to state a view, give a reason, add contrast when needed, and finish with a clear result or next step.',
        rules: ['Use meiner Meinung nach or ich finde, dass for your view.', 'Use weil, deshalb, obwohl, and trotzdem with correct word order.', 'Use einerseits and andererseits for balanced arguments.'],
        examples: [{ de: 'Meiner Meinung nach ist ein Online-Termin praktischer.', en: 'In my opinion, an online appointment is more practical.' }, { de: 'Einerseits ist die Wohnung teuer, andererseits liegt sie sehr zentral.', en: 'On one hand the apartment is expensive; on the other hand it is very central.' }, { de: 'Obwohl ich wenig Zeit habe, lerne ich jeden Tag Deutsch.', en: 'Although I have little time, I learn German every day.' }],
        tip: 'Use fewer connectors correctly instead of many connectors badly.',
        mistakes: ['Do not write Meiner Meinung nach es ist; use Meiner Meinung nach ist...', 'Do not use the same word order after obwohl and trotzdem.'],
        practice: ['Write a six-sentence opinion about online appointments.', 'Make one argument with einerseits, andererseits, weil, and trotzdem.'],
      },
    ],
  },
];

// ══════════════════════════════════════════════
// FORM-FOCUSED QUIZZES (gap-fill / form choice)
// q = question, a = correct answer, d = distractors. Options = [a, ...d] shuffled at render.
// ══════════════════════════════════════════════
const GRAMMAR_QUIZZES = {
  'a1-word-position': [
    { q: "Choose the correct order: 'Heute ___ zu Hause.'", a: 'arbeite ich', d: ['ich arbeite', 'arbeiten ich'] },
    { q: "Put the verb in position 2: 'Morgen ___ ich nach Berlin.' (fahren)", a: 'fahre', d: ['fährt', 'fahren'] },
    { q: "Negate correctly: 'Ich komme morgen.'", a: 'Ich komme morgen nicht.', d: ['Ich nicht komme morgen.', 'Ich komme nicht morgen.'] },
  ],
  'a1-verbs': [
    { q: "Complete: 'Du ___ Deutsch.' (lernen)", a: 'lernst', d: ['lernt', 'lernen'] },
    { q: "Finish the separable verb: 'Sie ruft Michael ___.'", a: 'an', d: ['auf', 'aus'] },
    { q: "Modal verb: 'Ich muss am Montag ___.' (arbeiten)", a: 'arbeiten', d: ['arbeite', 'gearbeitet'] },
  ],
  'a1-articles-nouns-nominative': [
    { q: "Choose the article: '___ Museum ist groß.'", a: 'Das', d: ['Der', 'Die'] },
    { q: "Negate the noun: 'Das ist ___ Kaffee.'", a: 'kein', d: ['nicht', 'keine'] },
    { q: "Plural negation: 'Das sind ___ Kinder.'", a: 'keine', d: ['kein', 'nicht'] },
  ],
  'a1-building-questions': [
    { q: "Ask about a destination: '___ gehst du?'", a: 'Wohin', d: ['Wo', 'Woher'] },
    { q: "Ask about origin: '___ kommst du?'", a: 'Woher', d: ['Wohin', 'Wo'] },
    { q: "Make a yes/no question from 'Du wohnst in Köln.'", a: 'Wohnst du in Köln?', d: ['Du wohnst in Köln?', 'Wohnst in Köln du?'] },
  ],
  'a1-adjectives': [
    { q: "Predicate adjective: 'Der Apfel ___ rot.'", a: 'ist', d: ['sind', 'bist'] },
    { q: "Negate: 'Die Bücher sind ___ teuer.'", a: 'nicht', d: ['kein', 'keine'] },
    { q: 'Which is correct (no ending after sein)?', a: 'Die Lehrerin ist freundlich.', d: ['Die Lehrerin ist freundliche.', 'Die freundliche Lehrerin ist.'] },
  ],
  'a1-articles-nouns-accusative': [
    { q: "Accusative masculine: 'Sie isst ___ Kuchen.'", a: 'den', d: ['der', 'dem'] },
    { q: "Accusative: 'Ich brauche ___ Termin.'", a: 'einen', d: ['ein', 'einem'] },
    { q: "Accusative pronoun (you, informal): 'Ich liebe ___.'", a: 'dich', d: ['dir', 'du'] },
  ],
  'a1-possessive-articles': [
    { q: "Choose (my): '___ Mutter heißt Anna.'", a: 'Meine', d: ['Mein', 'Meinen'] },
    { q: "Accusative (my): 'Ich suche ___ Schlüssel.'", a: 'meinen', d: ['mein', 'meine'] },
    { q: "Formal 'your': '___ Auto ist neu.'", a: 'Ihr', d: ['ihr', 'euer'] },
  ],
  'a1-past-tense-imperfect': [
    { q: "Simple past of sein: 'Ich ___ krank.'", a: 'war', d: ['bin', 'hatte'] },
    { q: "Simple past of haben: 'Du ___ gestern Spaß.'", a: 'hattest', d: ['warst', 'hast'] },
    { q: "There was a problem: '___ ein Problem.'", a: 'Es gab', d: ['Es gibt', 'Es hatte'] },
  ],
  'a1-building-good-sentences': [
    { q: 'TE-KA-MO-LO order — choose correct:', a: 'Ich fahre morgen mit dem Bus nach Köln.', d: ['Ich fahre mit dem Bus morgen nach Köln.', 'Ich fahre nach Köln morgen mit dem Bus.'] },
    { q: "Verb in position 2: 'Am Montag ___ ich.'", a: 'arbeite', d: ['ich arbeite', 'arbeiten'] },
    { q: 'Which question is correct?', a: 'Gefällt er dir?', d: ['Er gefällt dir?', 'Dir er gefällt?'] },
  ],
  'a1-imperative': [
    { q: "Informal (du): '___ das bitte noch einmal!' (sagen)", a: 'Sag', d: ['Sagst', 'Sagen'] },
    { q: "Formal (Sie): '___ Sie mir bitte Bescheid!' (sagen)", a: 'Sagen', d: ['Sag', 'Sagt'] },
    { q: "Separable imperative: 'Nimm deinen Ausweis ___!'", a: 'mit', d: ['an', 'auf'] },
  ],
  'a1-prepositions': [
    { q: "Dative after mit: 'Ich fahre mit ___ Bus.'", a: 'dem', d: ['den', 'der'] },
    { q: "Accusative preposition: 'Maria kann ___ Handy nicht leben.'", a: 'ohne', d: ['mit', 'von'] },
    { q: 'Which preposition takes the accusative?', a: 'für', d: ['mit', 'seit'] },
  ],
  'a1-past-tense-perfect': [
    { q: "Perfekt with haben: 'Ich ___ den Film gesehen.'", a: 'habe', d: ['bin', 'hatte'] },
    { q: "Perfekt with sein: 'Ich ___ nach Hause gegangen.'", a: 'bin', d: ['habe', 'war'] },
    { q: 'Participle at the end — choose correct:', a: 'Hast du den Film gesehen?', d: ['Hast du gesehen den Film?', 'Habst du den Film gesehen?'] },
  ],
  'a1-connecting-sentences': [
    { q: "Correction after a negative: 'Nicht am Montag, ___ am Mittwoch.'", a: 'sondern', d: ['aber', 'oder'] },
    { q: "Reason, verb stays in position 2: 'Sie hat keine Zeit, ___ sie arbeitet.'", a: 'denn', d: ['weil', 'dass'] },
    { q: "Join equal ideas: 'Pia wohnt in Berlin ___ arbeitet dort.'", a: 'und', d: ['sondern', 'denn'] },
  ],
  'a2-comparative-form': [
    { q: "Comparative: 'Der Zug ist ___ als der Bus.' (schnell)", a: 'schneller', d: ['schnell', 'am schnellsten'] },
    { q: "Irregular: 'Er spricht ___ Deutsch als seine Schwester.' (gut)", a: 'besser', d: ['guter', 'gutter'] },
    { q: "Use 'als' or 'wie'? 'schneller ___ der Bus'", a: 'als', d: ['wie', 'als wie'] },
  ],
  'a2-superlative': [
    { q: "Adverbial superlative: 'Er rennt ___.' (schnell)", a: 'am schnellsten', d: ['der schnellste', 'am schnelle'] },
    { q: "Before a noun: 'Er ist der ___ Läufer.' (schnell)", a: 'schnellste', d: ['am schnellsten', 'schnellster'] },
    { q: "Equal comparison: 'Er spricht ___ gut ___ ich.'", a: 'so … wie', d: ['als … wie', 'mehr … als'] },
  ],
  'a2-dative-accusative': [
    { q: "Order (dative before accusative): 'Ich schicke ___.'", a: 'dem Professor einen Brief', d: ['einen Brief dem Professor', 'den Professor einen Brief'] },
    { q: "Both pronouns (accusative before dative): 'Ich gebe ___.'", a: 'ihn dir', d: ['dir ihn', 'dir ihm'] },
    { q: "Dative article: 'Sie erklärt ___ Kunden den Vertrag.'", a: 'dem', d: ['den', 'der'] },
  ],
  'a2-modalverbs-imperfect': [
    { q: "Simple past: 'Wir ___ um 7 Uhr aufstehen.' (müssen)", a: 'mussten', d: ['mussen', 'müssten'] },
    { q: "Past of können: 'Ich ___ gestern nicht kommen.'", a: 'konnte', d: ['könnte', 'gekonnt'] },
    { q: 'Infinitive stays at the end — choose correct:', a: 'Er durfte nie Fahrrad fahren.', d: ['Er durfte nie Fahrrad fährt.', 'Er durfte nie fuhr Fahrrad.'] },
  ],
  'a2-connecting-sentences-2': [
    { q: "Verb to the end: 'Ich bleibe zu Hause, weil ich krank ___.'", a: 'bin', d: ['ist', 'sein'] },
    { q: 'Choose correct:', a: '…, weil es teuer ist.', d: ['…, weil es ist teuer.', '…, weil ist es teuer.'] },
    { q: "Fronted clause inversion: 'Weil ich keine Zeit habe, ___ ich nicht.'", a: 'komme', d: ['ich komme', 'kommen'] },
  ],
  'a2-wenn-falls-dann': [
    { q: "Verb-final in the condition: 'Wenn es morgen ___, bleiben wir zu Hause.' (regnen)", a: 'regnet', d: ['regnet es', 'es regnet'] },
    { q: "Main clause after a fronted wenn: 'Wenn es regnet, ___ wir zu Hause.'", a: 'bleiben', d: ['wir bleiben', 'dann wir bleiben'] },
    { q: 'Which word marks a less certain condition?', a: 'falls', d: ['dann', 'sondern'] },
  ],
  'a2-dass-sentences': [
    { q: "Verb to the end: 'Ich finde, dass er nett ___.'", a: 'ist', d: ['ist nett', 'sein'] },
    { q: "Modal at the end: 'Es ist schade, dass du nicht kommen ___.'", a: 'kannst', d: ['kannst nicht', 'kann'] },
    { q: "dass or das? 'Ich denke, ___ es regnet.'", a: 'dass', d: ['das', 'dasss'] },
  ],
  'a2-two-way-prepositions': [
    { q: "Direction (accusative): 'Ich gehe in ___ Supermarkt.'", a: 'den', d: ['dem', 'der'] },
    { q: "Location (dative): 'Ich bin ___ Supermarkt.'", a: 'im', d: ['in den', 'ins'] },
    { q: "Position verb: 'Der Brief ___ auf dem Tisch.'", a: 'liegt', d: ['legt', 'steht'] },
  ],
  'a2-konjunktiv-ii': [
    { q: "Polite request: '___ du mir bitte helfen?' (können)", a: 'Könntest', d: ['Kannst', 'Konntest'] },
    { q: "Wish: 'Ich ___ gerne einen Hund.' (haben)", a: 'hätte', d: ['habe', 'hatte'] },
    { q: "Unreal 'would': 'Ich ___ nie zu spät kommen.'", a: 'würde', d: ['werde', 'wurde'] },
  ],
  'a2-futur-i': [
    { q: "Futur I: 'Ich ___ morgen anrufen.'", a: 'werde', d: ['bin', 'wurde'] },
    { q: "Infinitive at the end: 'Wir werden die Unterlagen ___.'", a: 'prüfen', d: ['prüft', 'geprüft'] },
    { q: 'Choose correct:', a: 'Es wird wahrscheinlich regnen.', d: ['Es wird wahrscheinlich regnet.', 'Es werden wahrscheinlich regnen.'] },
  ],
  'a2-genitiv': [
    { q: "Feminine genitive: 'Das ist das Buch ___ Lehrerin.'", a: 'der', d: ['des', 'dem'] },
    { q: "Masculine genitive: 'Das ist das Buch ___.' (der Lehrer)", a: 'des Lehrers', d: ['dem Lehrer', 'der Lehrer'] },
    { q: 'Which question word asks about possession?', a: 'Wessen', d: ['Wer', 'Wem'] },
  ],
  'a2-pronouns': [
    { q: "Accusative of jemand: 'Kennst du ___ hier?'", a: 'jemanden', d: ['jemand', 'jemandem'] },
    { q: "'man' in the accusative becomes:", a: 'einen', d: ['man', 'einem'] },
    { q: "Choose correct (none, masc.): 'Ich habe ___.'", a: 'keinen', d: ['kein', 'keine'] },
  ],
  'a2-reflective-verbs': [
    { q: "Accusative reflexive: 'Ich melde ___ online an.'", a: 'mich', d: ['mir', 'sich'] },
    { q: "Dative reflexive (other object present): 'Ich notiere ___ die Adresse.'", a: 'mir', d: ['mich', 'sich'] },
    { q: "Choose correct: 'Sie freut ___ auf den Urlaub.'", a: 'sich', d: ['ihr', 'sie'] },
  ],
  'a2-adjective-declinations': [
    { q: "After 'einen' (masc. acc.): 'Ich brauche einen ___ Termin.' (neu)", a: 'neuen', d: ['neuer', 'neue'] },
    { q: "After 'die' (fem. nom.): 'Die ___ Adresse ist richtig.' (neu)", a: 'neue', d: ['neuen', 'neuer'] },
    { q: "After 'ein' (neut.): 'Haben Sie ein ___ Formular?' (ander-)", a: 'anderes', d: ['andere', 'anderen'] },
  ],
  'a2-n-declination': [
    { q: "Weak noun accusative: 'Ich frage den ___.' (Kollege)", a: 'Kollegen', d: ['Kollege', 'Kolleg'] },
    { q: "Dative: 'Ich helfe dem ___.' (Nachbar)", a: 'Nachbarn', d: ['Nachbar', 'Nachbaren'] },
    { q: "Genitive: 'Der Name des ___ fehlt.' (Kunde)", a: 'Kunden', d: ['Kunde', 'Kundes'] },
  ],
  'a2-prepositional-objects': [
    { q: "Verb + preposition: 'Ich warte ___ den Bus.'", a: 'auf', d: ['für', 'an'] },
    { q: "Case after 'warten auf': 'Ich warte auf ___ Bus.'", a: 'den', d: ['dem', 'der'] },
    { q: "'sich interessieren ___' + accusative", a: 'für', d: ['an', 'über'] },
  ],
  'a2-imperfect-tense': [
    { q: "Weak Präteritum: 'Er ___ ein Geschenk.' (kaufen)", a: 'kaufte', d: ['kaufen', 'gekauft'] },
    { q: "Strong Präteritum: 'Er ___ nach Hause.' (gehen)", a: 'ging', d: ['gehte', 'gegangen'] },
    { q: "Mixed verb: 'Er ___ die Antwort nicht.' (wissen)", a: 'wusste', d: ['wisste', 'gewusst'] },
  ],
  'b1-konjunktiv-ii-deepening': [
    { q: "Unreal present: 'Wenn ich mehr Zeit ___, würde ich mehr üben.' (haben)", a: 'hätte', d: ['habe', 'hatte'] },
    { q: "Past unreal: 'Ich ___ früher gekommen, wenn der Zug pünktlich gewesen wäre.' (sein)", a: 'wäre', d: ['würde', 'hätte'] },
    { q: "Shortest natural form for 'could':", a: 'könnte', d: ['würde können', 'konnte'] },
  ],
  'b1-passive': [
    { q: "Present passive: 'Der Antrag ___ geprüft.'", a: 'wird', d: ['ist', 'hat'] },
    { q: "Past passive: 'Die Unterlagen ___ geschickt.'", a: 'wurden', d: ['sind', 'haben'] },
    { q: 'Participle at the end — choose correct:', a: 'Die Rechnung wird automatisch bezahlt.', d: ['Die Rechnung wird bezahlt automatisch.', 'Die Rechnung bezahlt wird automatisch.'] },
  ],
  'b1-temporal-clauses': [
    { q: 'A one-time past event uses:', a: 'als', d: ['wenn', 'wann'] },
    { q: 'A repeated event or future condition uses:', a: 'wenn', d: ['als', 'während'] },
    { q: "Sequence 'before': 'Ich prüfe alles, ___ ich den Antrag schicke.'", a: 'bevor', d: ['nachdem', 'seitdem'] },
  ],
  'b1-relative-clauses-cases': [
    { q: "Subject pronoun (masc.): 'Der Mann, ___ dort wartet, …'", a: 'der', d: ['den', 'dem'] },
    { q: "Object pronoun (neut., accusative): 'Das Formular, ___ ich brauche, …'", a: 'das', d: ['dem', 'der'] },
    { q: "Dative pronoun: 'Die Kollegin, ___ ich geschrieben habe, …'", a: 'der', d: ['die', 'den'] },
  ],
  'b1-purpose-clauses': [
    { q: 'Same subject for both actions — use:', a: 'um … zu', d: ['damit', 'weil'] },
    { q: "Different subjects: 'Ich schicke den Link, ___ Sie das Formular finden.'", a: 'damit', d: ['um zu', 'sodass'] },
    { q: "Separable verb with zu: 'Sie ruft an, um den Termin ___.' (absagen)", a: 'abzusagen', d: ['zu absagen', 'absagen zu'] },
  ],
  'b1-infinitive-clauses': [
    { q: "'without doing': 'Er ging, ___ sich zu verabschieden.'", a: 'ohne', d: ['statt', 'um'] },
    { q: "'instead of': 'Sie schrieb eine E-Mail, ___ anzurufen.'", a: 'statt', d: ['ohne', 'um'] },
    { q: "zu + infinitive: 'Ich versuche, den Antrag ___.' (ausfüllen)", a: 'auszufüllen', d: ['ausfüllen', 'zu ausfüllen'] },
  ],
  'b1-passive-modal-verbs': [
    { q: "Modal + passive: 'Der Antrag muss online gestellt ___.'", a: 'werden', d: ['sein', 'worden'] },
    { q: 'Choose correct:', a: 'Die Rechnung kann später bezahlt werden.', d: ['Die Rechnung kann später werden bezahlt.', 'Die Rechnung kann später bezahlt sein.'] },
    { q: "Negation: 'Die Unterlagen ___ nicht kopiert werden.' (dürfen)", a: 'dürfen', d: ['darf', 'durften'] },
  ],
  'b1-paired-connectors': [
    { q: "Alternatives: '___ anrufen ___ eine E-Mail schreiben'", a: 'entweder … oder', d: ['weder … noch', 'sowohl … als auch'] },
    { q: "Double negative: 'Ich habe ___ Zeit ___ Geld.'", a: 'weder … noch', d: ['entweder … oder', 'nicht nur … sondern auch'] },
    { q: "Both positive: 'Der Kurs ist ___ praktisch ___ interessant.'", a: 'sowohl … als auch', d: ['weder … noch', 'entweder … oder'] },
  ],
  'b1-genitive-prepositions': [
    { q: "Reason (genitive): '___ des Wetters fällt der Termin aus.'", a: 'Wegen', d: ['Trotz', 'Während'] },
    { q: "Contrast: '___ des Regens kam sie pünktlich.'", a: 'Trotz', d: ['Wegen', 'Innerhalb'] },
    { q: "Noun ending: 'wegen des ___' (Vertrag)", a: 'Vertrags', d: ['Vertrag', 'Vertragen'] },
  ],
  'b1-noun-verb-combinations': [
    { q: "Fixed expression: 'Wir müssen eine Entscheidung ___.'", a: 'treffen', d: ['machen', 'nehmen'] },
    { q: "'contact us': 'Bitte nehmen Sie mit uns ___ auf.'", a: 'Kontakt', d: ['Verbindung', 'Bescheid'] },
    { q: "'comes into effect': 'Die Regel tritt morgen ___.'", a: 'in Kraft', d: ['in Ordnung', 'in Frage'] },
  ],
  'b1-future-assumptions': [
    { q: "Assumption: 'Er ___ wohl noch im Büro sein.'", a: 'wird', d: ['ist', 'hat'] },
    { q: "Futur II ending: 'Sie wird den Brief schon bekommen ___.'", a: 'haben', d: ['sein', 'worden'] },
    { q: "Future promise: 'Ich ___ Ihnen morgen antworten.'", a: 'werde', d: ['wurde', 'würde'] },
  ],
  'b1-relative-clauses-prepositions': [
    { q: "Preposition + pronoun: 'die Frau, ___ ich gesprochen habe' (mit)", a: 'mit der', d: ['mit die', 'der mit'] },
    { q: "'der Kurs, ___ ich mich interessiere' (für)", a: 'für den', d: ['für dem', 'für der'] },
    { q: "Don't strand the preposition — choose correct:", a: 'das Problem, über das wir sprechen', d: ['das Problem, das wir sprechen über', 'das Problem, über dem wir sprechen'] },
  ],
  'b1-da-wo-compounds': [
    { q: "da-compound for 'auf das': 'Ich warte ___.'", a: 'darauf', d: ['auf das', 'darüber'] },
    { q: "wo-compound question: '___ warten Sie?'", a: 'Worauf', d: ['Worüber', 'Wofür'] },
    { q: "'mit dem' becomes:", a: 'damit', d: ['mitdem', 'darmit'] },
  ],
  'b1-plusquamperfekt': [
    { q: "haben-verb: 'Ich ___ den Antrag schon geschickt.'", a: 'hatte', d: ['habe', 'war'] },
    { q: "sein-verb: 'Als ich ankam, ___ der Arzt schon gegangen.'", a: 'war', d: ['hatte', 'ist'] },
    { q: 'Choose correct (past before past):', a: 'Ich hatte die Rechnung bezahlt.', d: ['Ich habe die Rechnung bezahlt hatte.', 'Ich war die Rechnung bezahlt.'] },
  ],
  'b1-reported-information': [
    { q: "Report an instruction: 'Ich ___ das Formular online hochladen.'", a: 'soll', d: ['will', 'mag'] },
    { q: "According to a letter: '___ Brief ist die Zahlung offen.'", a: 'Laut', d: ['Wegen', 'Trotz'] },
    { q: "Verb-final after dass: 'Sie sagt, dass ich eine Kopie ___.'", a: 'brauche', d: ['brauche nicht', 'brauchen'] },
  ],
  'b1-participle-adjectives': [
    { q: "Partizip I (ongoing): 'die ___ Unterlagen' (fehlen)", a: 'fehlenden', d: ['gefehlten', 'fehlten'] },
    { q: "Partizip II (completed): 'die ___ Rechnung' (bezahlen)", a: 'bezahlte', d: ['bezahlende', 'bezahlt'] },
    { q: "With ending: 'Ich suche einen ___ Termin.' (passen)", a: 'passenden', d: ['passend', 'gepasst'] },
  ],
  'b1-nominal-style': [
    { q: "Verb → noun: 'prüfen' becomes 'die ___'", a: 'Prüfung', d: ['Prüfheit', 'Prüfschaft'] },
    { q: 'Most -ung nouns have which gender?', a: 'feminine (die)', d: ['masculine (der)', 'neuter (das)'] },
    { q: "'die Anmeldung' comes from which verb?", a: 'anmelden', d: ['anmelten', 'melden'] },
  ],
  'b1-opinion-argument-structure': [
    { q: 'Correct word order — choose:', a: 'Meiner Meinung nach ist das praktischer.', d: ['Meiner Meinung nach das ist praktischer.', 'Meiner Meinung nach es ist praktischer.'] },
    { q: "Concession: '___ ich wenig Zeit habe, lerne ich täglich.'", a: 'Obwohl', d: ['Trotzdem', 'Deshalb'] },
    { q: "Balanced argument: '___ teuer, ___ zentral.'", a: 'einerseits … andererseits', d: ['entweder … oder', 'weder … noch'] },
  ],
};

const GRAMMAR_LESSONS = GRAMMAR_MODULES.flatMap(module => module.lessons.map(lesson => ({ ...lesson, moduleId: module.id, level: module.level, quiz: GRAMMAR_QUIZZES[lesson.id] || [] })));
const GRAMMAR_MODULE_BY_ID = Object.fromEntries(GRAMMAR_MODULES.map(module => [module.id, module]));
